modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="armorplus" #mandatory
version="1.0" #mandatory
displayName="Armor+" #mandatory
credits="1" #optional
authors="idrk" #optional
description='''
lol hi

this is

a description
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.armorplus]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.armorplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
